"""
EvoPop: A post-processing pipeline for 3D meshes generated by GANular, including artefact removal, manifold repair, triangle reduction, and smoothing.
"""

from .processing import (
    MeshPipeline,
    MeshRepair,
    ReduceTriangles,
    SmoothMesh,
    SimpleThreshold,
    Otsu3DThreshold,
    TopologyAware3DSegmenter,
)

from .shape_factors import (
    compute_shape_factors,
    compute_shape_factors_3d,
    common_mesh_scale,
    resample_outline,
)

from .particle_selection import (
    GeneratedParticlePool,
    OptimisationResult,
    ShapeOptimiser,
    estimate_target_distribution,
    select_best_epoch,
)

__all__ = [
    "MeshPipeline",
    "MeshRepair",
    "ReduceTriangles",
    "SmoothMesh",
    "estimate_target_distribution",
    "select_best_epoch",
    "OptimisationResult",
    "ShapeOptimiser",
    "GeneratedParticlePool",
    "SimpleThreshold",
    "Otsu3DThreshold",
    "TopologyAware3DSegmenter",
    "compute_shape_factors",
    "compute_shape_factors_3d",
    "common_mesh_scale",
    "resample_outline",
]
